In [21]:
import os 
import numpy as np
import pandas as pd 
import anndata as ad

In [ ]:
### use 100G

### Testing

In [2]:
tdata = ad.read_h5ad("sample_out/MM_1341_1_2_MM_1337_1_2.h5ad")

In [7]:
tdata2 = ad.read_h5ad("sample_out/MM_1342_1_2_MM_1338_1_2.h5ad")

In [8]:
tdata.var

                         chr     start      stop
chr1_9820_10319         chr1      9820     10319
chr1_15904_16403        chr1     15904     16403
chr1_17129_17628        chr1     17129     17628
chr1_102622_103121      chr1    102622    103121
chr1_136384_136883      chr1    136384    136883
...                      ...       ...       ...
chrY_56869493_56869992  chrY  56869493  56869992
chrY_56870649_56871148  chrY  56870649  56871148
chrY_56873404_56873903  chrY  56873404  56873903
chrY_56877440_56877939  chrY  56877440  56877939
chrY_56879599_56880098  chrY  56879599  56880098

[560820 rows x 3 columns]

In [9]:
tdata2.var

                         chr     start      stop
chr1_9820_10319         chr1      9820     10319
chr1_15904_16403        chr1     15904     16403
chr1_17129_17628        chr1     17129     17628
chr1_102622_103121      chr1    102622    103121
chr1_136384_136883      chr1    136384    136883
...                      ...       ...       ...
chrY_56869493_56869992  chrY  56869493  56869992
chrY_56870649_56871148  chrY  56870649  56871148
chrY_56873404_56873903  chrY  56873404  56873903
chrY_56877440_56877939  chrY  56877440  56877939
chrY_56879599_56880098  chrY  56879599  56880098

[560820 rows x 3 columns]

In [ ]:
#### Features look synced up and ready to go

### Concat adatas

In [ ]:
### Iterate and read adatas
### Then ad.concat 
### Full ATAC obj complete!

In [22]:
os.listdir("sample_out/")

['pairedTag_2556.h5ad',
 'QY_2593_QY_2592.h5ad',
 'QY_2595_QY_2594.h5ad',
 'QY_2585_QY_2584.h5ad',
 'QY_2577_QY_2576.h5ad',
 'QY_2587_QY_2586.h5ad',
 'QY_2579_QY_2578.h5ad']

In [23]:
ad_list = list()

In [19]:
ad.read_h5ad('/tscc/projects/ps-epigen/users/rlan/LFNIH_Pt2/Pairtag/Build_ac_mat/sample_out/pairedTag_2556.h5ad')

AnnData object with n_obs × n_vars = 14249 × 226862
    var: 'chr', 'start', 'stop'

In [ ]:
### Looks like metadata needs to be fixed again
### Samples in metadata need to match fragment name??

In [25]:
for f in os.listdir("sample_out/"):
    adata = ad.read_h5ad(f'/tscc/projects/ps-epigen/users/rlan/LFNIH_Pt2/Pairtag/Build_ac_mat/sample_out/{f}')
    sample = f.strip('.h5ad')
    adata.obs['sample'] = sample 
   # print(sample)
    ### add sample obs 
    ad_list.append(adata)

In [26]:
ad_list

[AnnData object with n_obs × n_vars = 14249 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop',
 AnnData object with n_obs × n_vars = 15345 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop',
 AnnData object with n_obs × n_vars = 14449 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop',
 AnnData object with n_obs × n_vars = 12108 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop',
 AnnData object with n_obs × n_vars = 13023 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop',
 AnnData object with n_obs × n_vars = 12342 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop',
 AnnData object with n_obs × n_vars = 13246 × 226862
     obs: 'sample'
     var: 'chr', 'start', 'stop']

In [27]:
mdata = ad.concat(ad_list)

In [28]:
mdata

AnnData object with n_obs × n_vars = 94762 × 226862
    obs: 'sample'

In [29]:
len(mdata.obs)

94762

In [10]:
del(ad_list)

In [30]:
### use ac meta 
metadata = pd.read_csv("/tscc/projects/ps-epigen/users/rlan/LFNIH_Pt2/Pairtag/Build_ac_mat/corr_ac_meta.csv", index_col=0)

In [31]:
metadata['assay'].unique()

array(['k27ac'], dtype=object)

In [33]:
metadata['sample'].unique()

array(['pairedTag_2556', 'QY_2577_QY_2576', 'QY_2579_QY_2578',
       'QY_2585_QY_2584', 'QY_2587_QY_2586', 'QY_2593_QY_2592',
       'QY_2595_QY_2594'], dtype=object)

In [39]:
metadata = metadata.drop(columns=['sample'])

In [40]:
mdata.obs

                                             sample
pairedTag_2556_GGCTAGTGTGTGTGGT-1    pairedTag_2556
pairedTag_2556_GGCTAGTGTTACATCC-1    pairedTag_2556
pairedTag_2556_GTTTAACCACCCTCAC-1    pairedTag_2556
pairedTag_2556_GTTTAACCATGTCGCG-1    pairedTag_2556
pairedTag_2556_GTTTAACCAACAGGTG-1    pairedTag_2556
...                                             ...
QY_2579_QY_2578_GGTAAACCAGCTTAGC-1  QY_2579_QY_2578
QY_2579_QY_2578_GGTAAACCAGAATGAC-1  QY_2579_QY_2578
QY_2579_QY_2578_GGTAAACCATAAACCT-1  QY_2579_QY_2578
QY_2579_QY_2578_GGTAAACCAGCTTAAT-1  QY_2579_QY_2578
QY_2579_QY_2578_GGTAAACCACTAAGCC-1  QY_2579_QY_2578

[94762 rows x 1 columns]

In [41]:
new_meta = mdata.obs.join(metadata)

In [42]:
mdata.obs = new_meta

In [43]:
### Subset for Heps

In [44]:
mdata.obs

,sample,donor,donor_assay,nCount_RNA,nFeature_RNA,percent.mt,celltype,subcelltype,batch,assay,donors_combined,alcohol,Steatosis.grade,Fibrosis.stage,condition,barcode
pairedTag_2556_GGCTAGTGTGTGTGGT-1,pairedTag_2556,HL221006,HL221006_pairtag,602,468,0.164204,Myeloid,Kupffer,10252023.0,k27ac,HL221006,Y,2.0,1.0,MASH,GGCTAGTGTGTGTGGT-1
pairedTag_2556_GGCTAGTGTTACATCC-1,pairedTag_2556,HL211122,HL211122_pairtag,405,372,0.000000,Myeloid,Macrophage,10252023.0,k27ac,HL211122,Y,2.0,3.0,MetALD,GGCTAGTGTTACATCC-1
pairedTag_2556_GTTTAACCACCCTCAC-1,pairedTag_2556,HL211122,HL211122_pairtag,2406,1481,0.000000,Hepatocytes,Hepatocytes.Zone3,10252023.0,k27ac,HL211122,Y,2.0,3.0,MetALD,GTTTAACCACCCTCAC-1
pairedTag_2556_GTTTAACCATGTCGCG-1,pairedTag_2556,HL210207,HL210207_pairtag,1025,747,0.000000,Endothelial,Sinusoidal.Endothelial,10252023.0,k27ac,HL210207,N,0.0,0.0,Control,GTTTAACCATGTCGCG-1
pairedTag_2556_GTTTAACCAACAGGTG-1,pairedTag_2556,HL180809,HL180809_pairtag,2973,1737,0.000000,Hepatocytes,Hepatocytes.Zone2,10252023.0,k27ac,HL180809,N,0.0,0.0,Control,GTTTAACCAACAGGTG-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
QY_2579_QY_2578_GGTAAACCAGCTTAGC-1,QY_2579_QY_2578,HL160029,HL160029_pairtag,7026,3038,0.013782,Hepatocytes,Hepatocytes.Zone1,8012023.0,k27ac,HL160029,N,0.0,0.0,Control,GGTAAACCAGCTTAGC-1
QY_2579_QY_2578_GGTAAACCAGAATGAC-1,QY_2579_QY_2578,HL190214,HL190214_pairtag,3338,1694,0.029265,Endothelial,Sinusoidal.Endothelial,2262024.0,k27ac,HL190214,N,0.0,0.0,Control,GGTAAACCAGAATGAC-1
QY_2579_QY_2578_GGTAAACCATAAACCT-1,QY_2579_QY_2578,HL170060,HL170060_pairtag,15716,4663,0.005732,Endothelial,Vascular.Endothelial,8012023.0,k27ac,HL170060,Y,3.0,2.0,MetALD,GGTAAACCATAAACCT-1
QY_2579_QY_2578_GGTAAACCAGCTTAAT-1,QY_2579_QY_2578,HL160029,HL160029_pairtag,8333,3293,0.000000,Hepatocytes,Hepatocytes.Zone1,8012023.0,k27ac,HL160029,N,0.0,0.0,Control,GGTAAACCAGCTTAAT-1
QY_2579_QY_2578_GGTAAACCACTAAGCC-1,QY_2579_QY_2578,HL210726,HL210726_pairtag,7036,3058,0.000000,Hepatocytes,Hepatocytes.Senescent,8012023.0,k27ac,HL210726,N,3.0,4.0,MASH,GGTAAACCACTAAGCC-1

In [45]:
os.makedirs('merged_objects', exist_ok=True)

In [46]:
mdata.write_h5ad("merged_objects/lfnih_k27ac_raw.h5ad")